# Theme Configuration
remote_theme: pages-themes/minimal@v0.2.0

# Site Title & Description
title: Hello Processing
description: ğŸ‘»ğŸ•¯ğŸƒğŸ•¸ğŸ¦‡ October Lessons ğŸ‘»ğŸ•¯ğŸƒğŸ•¸ğŸ¦‡

# Minima Theme Customization
minima:
  skin: solarized-dark

# Header Configuration
header_pages:
  - README.md

# Author Information
author:
  name: Lila James
  email: ljames@riverdale.edu

# Plugins
plugins:
  - jekyll-remote-theme
